// Code generated by local/scripts/gen-massive-venue-map.py; DO NOT EDIT.

package massive

// venues holds the MIC of each US exchange where Massive lists stock.
var venues = map[string]bool{
	"ARCX": true,
	"BATS": true,
	"BATY": true,
	"EDGA": true,
	"EDGX": true,
	"IEXG": true,
	"XASE": true,
	"XBOS": true,
	"XCHI": true,
	"XCIS": true,
	"XNAS": true,
	"XNYS": true,
	"XPHL": true,
}
